user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

general:
    resource: "@GeneralBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
