# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            sha256
        UserBundle\Entity\Users:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        user:
            entity: { class: UserBundle\Entity\Users, property: email }

    firewalls:
        default:
            pattern: ^/
            anonymous: true
            provider: user
            form_login:
                login_path: user_login
                check_path: user_login_post
                username_parameter: "user_login[email]"
                password_parameter: "user_login[password]"
                csrf_parameter: "user_login[_token]"
                csrf_provider: form.csrf_provider
                intention: authentication
            logout:
                path: user_logout
                target: /

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }