home_homepage:
    resource: "@HomeBundle/Controller/HomeController.php"
    prefix:   /
    type:     annotation

test_route_page:
    resource: "@HomeBundle/Controller/TestRouteController.php"
    prefix:   /test_route
    type:     annotation
