homepage:
    resource: "@AppBundle/Controller/HomeController.php"
    prefix:   /
    type:     annotation

vocabulary:
    resource: "@AppBundle/Controller/Vocabulary/"
    prefix:   /vocabulary
    type:     annotation

vocabulary_tree:
    resource: "@AppBundle/Controller/VocabularyTree/"
    prefix:   /tree
    type:     annotation

vocabulary_words:
    resource: "@AppBundle/Controller/VocabularyWords/"
    prefix:   /tree
    type:     annotation

learn_words:
    resource: "@AppBundle/Controller/Learn/"
    prefix:   /learn
    type:     annotation