homepage:
    resource: "@AppBundle/Controller/HomeController.php"
    prefix:   /
    type:     annotation

vocabulary:
    resource: "@AppBundle/Controller/Vocabulary/"
    prefix:   /vocabulary
    type:     annotation

vocabulary_tree:
    resource: "@AppBundle/Controller/VocabularyTree/"
    prefix:   /tree
    type:     annotation