
user_registration:
    resource: "@UserBundle/Controller/RegistrationController.php"
    prefix:   /user/registration
    type:     annotation

user_login:
    resource: "@UserBundle/Controller/LoginController.php"
    prefix:   /user/login
    type:     annotation

user_logout:
    resource: "@UserBundle/Controller/LogoutController.php"
    prefix:   /user/logout
    type:     annotation

test_route_page:
    resource: "@HomeBundle/Controller/TestRouteController.php"
    prefix:   /test_route
    type:     annotation
